// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fetch_msg_types.proto

// XXX - this project is cloning viaduct support from app-services as a short
// term hack while we work out a viable long-term strategy.
// We've copied these hand-written sources over, and rather than copying the
// .proto files and the protobuf build process, we just copied this generated
// file and changed package names.

package uniffi.nimbus.httpconfig;

public final class MsgTypes {
  private MsgTypes() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:uniffi.nimbus.httpconfig.protobuf.Request)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required .uniffi.nimbus.httpconfig.protobuf.Request.Method method = 1;</code>
     * @return Whether the method field is set.
     */
    boolean hasMethod();
    /**
     * <code>required .uniffi.nimbus.httpconfig.protobuf.Request.Method method = 1;</code>
     * @return The method.
     */
    uniffi.nimbus.httpconfig.MsgTypes.Request.Method getMethod();

    /**
     * <code>required string url = 2;</code>
     * @return Whether the url field is set.
     */
    boolean hasUrl();
    /**
     * <code>required string url = 2;</code>
     * @return The url.
     */
    java.lang.String getUrl();
    /**
     * <code>required string url = 2;</code>
     * @return The bytes for url.
     */
    com.google.protobuf.ByteString
        getUrlBytes();

    /**
     * <code>optional bytes body = 3;</code>
     * @return Whether the body field is set.
     */
    boolean hasBody();
    /**
     * <code>optional bytes body = 3;</code>
     * @return The body.
     */
    com.google.protobuf.ByteString getBody();

    /**
     * <code>map&lt;string, string&gt; headers = 4;</code>
     */
    int getHeadersCount();
    /**
     * <code>map&lt;string, string&gt; headers = 4;</code>
     */
    boolean containsHeaders(
        java.lang.String key);
    /**
     * Use {@link #getHeadersMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getHeaders();
    /**
     * <code>map&lt;string, string&gt; headers = 4;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getHeadersMap();
    /**
     * <code>map&lt;string, string&gt; headers = 4;</code>
     */

    java.lang.String getHeadersOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; headers = 4;</code>
     */

    java.lang.String getHeadersOrThrow(
        java.lang.String key);

    /**
     * <code>required bool follow_redirects = 5;</code>
     * @return Whether the followRedirects field is set.
     */
    boolean hasFollowRedirects();
    /**
     * <code>required bool follow_redirects = 5;</code>
     * @return The followRedirects.
     */
    boolean getFollowRedirects();

    /**
     * <code>required bool use_caches = 6;</code>
     * @return Whether the useCaches field is set.
     */
    boolean hasUseCaches();
    /**
     * <code>required bool use_caches = 6;</code>
     * @return The useCaches.
     */
    boolean getUseCaches();

    /**
     * <code>required int32 connect_timeout_secs = 7;</code>
     * @return Whether the connectTimeoutSecs field is set.
     */
    boolean hasConnectTimeoutSecs();
    /**
     * <code>required int32 connect_timeout_secs = 7;</code>
     * @return The connectTimeoutSecs.
     */
    int getConnectTimeoutSecs();

    /**
     * <code>required int32 read_timeout_secs = 8;</code>
     * @return Whether the readTimeoutSecs field is set.
     */
    boolean hasReadTimeoutSecs();
    /**
     * <code>required int32 read_timeout_secs = 8;</code>
     * @return The readTimeoutSecs.
     */
    int getReadTimeoutSecs();
  }
  /**
   * Protobuf type {@code uniffi.nimbus.httpconfig.protobuf.Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessageLite<
          Request, Request.Builder> implements
      // @@protoc_insertion_point(message_implements:uniffi.nimbus.httpconfig.protobuf.Request)
      RequestOrBuilder {
    private Request() {
      url_ = "";
      body_ = com.google.protobuf.ByteString.EMPTY;
    }
    /**
     * Protobuf enum {@code uniffi.nimbus.httpconfig.protobuf.Request.Method}
     */
    public enum Method
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <code>GET = 0;</code>
       */
      GET(0),
      /**
       * <code>HEAD = 1;</code>
       */
      HEAD(1),
      /**
       * <code>POST = 2;</code>
       */
      POST(2),
      /**
       * <code>PUT = 3;</code>
       */
      PUT(3),
      /**
       * <code>DELETE = 4;</code>
       */
      DELETE(4),
      /**
       * <code>CONNECT = 5;</code>
       */
      CONNECT(5),
      /**
       * <code>OPTIONS = 6;</code>
       */
      OPTIONS(6),
      /**
       * <code>TRACE = 7;</code>
       */
      TRACE(7),
      ;

      /**
       * <code>GET = 0;</code>
       */
      public static final int GET_VALUE = 0;
      /**
       * <code>HEAD = 1;</code>
       */
      public static final int HEAD_VALUE = 1;
      /**
       * <code>POST = 2;</code>
       */
      public static final int POST_VALUE = 2;
      /**
       * <code>PUT = 3;</code>
       */
      public static final int PUT_VALUE = 3;
      /**
       * <code>DELETE = 4;</code>
       */
      public static final int DELETE_VALUE = 4;
      /**
       * <code>CONNECT = 5;</code>
       */
      public static final int CONNECT_VALUE = 5;
      /**
       * <code>OPTIONS = 6;</code>
       */
      public static final int OPTIONS_VALUE = 6;
      /**
       * <code>TRACE = 7;</code>
       */
      public static final int TRACE_VALUE = 7;


      @java.lang.Override
      public final int getNumber() {
        return value;
      }

      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Method valueOf(int value) {
        return forNumber(value);
      }

      public static Method forNumber(int value) {
        switch (value) {
          case 0: return GET;
          case 1: return HEAD;
          case 2: return POST;
          case 3: return PUT;
          case 4: return DELETE;
          case 5: return CONNECT;
          case 6: return OPTIONS;
          case 7: return TRACE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Method>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Method> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Method>() {
              @java.lang.Override
              public Method findValueByNumber(int number) {
                return Method.forNumber(number);
              }
            };

      public static com.google.protobuf.Internal.EnumVerifier 
          internalGetVerifier() {
        return MethodVerifier.INSTANCE;
      }

      private static final class MethodVerifier implements 
           com.google.protobuf.Internal.EnumVerifier { 
              static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new MethodVerifier();
              @java.lang.Override
              public boolean isInRange(int number) {
                return Method.forNumber(number) != null;
              }
            };

      private final int value;

      private Method(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:uniffi.nimbus.httpconfig.protobuf.Request.Method)
    }

    private int bitField0_;
    public static final int METHOD_FIELD_NUMBER = 1;
    private int method_;
    /**
     * <code>required .uniffi.nimbus.httpconfig.protobuf.Request.Method method = 1;</code>
     * @return Whether the method field is set.
     */
    @java.lang.Override
    public boolean hasMethod() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .uniffi.nimbus.httpconfig.protobuf.Request.Method method = 1;</code>
     * @return The method.
     */
    @java.lang.Override
    public uniffi.nimbus.httpconfig.MsgTypes.Request.Method getMethod() {
      uniffi.nimbus.httpconfig.MsgTypes.Request.Method result = uniffi.nimbus.httpconfig.MsgTypes.Request.Method.forNumber(method_);
      return result == null ? uniffi.nimbus.httpconfig.MsgTypes.Request.Method.GET : result;
    }
    /**
     * <code>required .uniffi.nimbus.httpconfig.protobuf.Request.Method method = 1;</code>
     * @param value The method to set.
     */
    private void setMethod(uniffi.nimbus.httpconfig.MsgTypes.Request.Method value) {
      method_ = value.getNumber();
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>required .uniffi.nimbus.httpconfig.protobuf.Request.Method method = 1;</code>
     */
    private void clearMethod() {
      bitField0_ = (bitField0_ & ~0x00000001);
      method_ = 0;
    }

    public static final int URL_FIELD_NUMBER = 2;
    private java.lang.String url_;
    /**
     * <code>required string url = 2;</code>
     * @return Whether the url field is set.
     */
    @java.lang.Override
    public boolean hasUrl() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string url = 2;</code>
     * @return The url.
     */
    @java.lang.Override
    public java.lang.String getUrl() {
      return url_;
    }
    /**
     * <code>required string url = 2;</code>
     * @return The bytes for url.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUrlBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(url_);
    }
    /**
     * <code>required string url = 2;</code>
     * @param value The url to set.
     */
    private void setUrl(
        java.lang.String value) {
      value.getClass();
  bitField0_ |= 0x00000002;
      url_ = value;
    }
    /**
     * <code>required string url = 2;</code>
     */
    private void clearUrl() {
      bitField0_ = (bitField0_ & ~0x00000002);
      url_ = getDefaultInstance().getUrl();
    }
    /**
     * <code>required string url = 2;</code>
     * @param value The bytes for url to set.
     */
    private void setUrlBytes(
        com.google.protobuf.ByteString value) {
      url_ = value.toStringUtf8();
      bitField0_ |= 0x00000002;
    }

    public static final int BODY_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString body_;
    /**
     * <code>optional bytes body = 3;</code>
     * @return Whether the body field is set.
     */
    @java.lang.Override
    public boolean hasBody() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional bytes body = 3;</code>
     * @return The body.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }
    /**
     * <code>optional bytes body = 3;</code>
     * @param value The body to set.
     */
    private void setBody(com.google.protobuf.ByteString value) {
      value.getClass();
  bitField0_ |= 0x00000004;
      body_ = value;
    }
    /**
     * <code>optional bytes body = 3;</code>
     */
    private void clearBody() {
      bitField0_ = (bitField0_ & ~0x00000004);
      body_ = getDefaultInstance().getBody();
    }

    public static final int HEADERS_FIELD_NUMBER = 4;
    private static final class HeadersDefaultEntryHolder {
      static final com.google.protobuf.MapEntryLite<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntryLite
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapFieldLite<
        java.lang.String, java.lang.String> headers_ =
            com.google.protobuf.MapFieldLite.emptyMapField();
    private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.String>
    internalGetHeaders() {
      return headers_;
    }
    private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.String>
    internalGetMutableHeaders() {
      if (!headers_.isMutable()) {
        headers_ = headers_.mutableCopy();
      }
      return headers_;
    }
    @java.lang.Override

    public int getHeadersCount() {
      return internalGetHeaders().size();
    }
    /**
     * <code>map&lt;string, string&gt; headers = 4;</code>
     */
    @java.lang.Override

    public boolean containsHeaders(
        java.lang.String key) {
      key.getClass();
      return internalGetHeaders().containsKey(key);
    }
    /**
     * Use {@link #getHeadersMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getHeaders() {
      return getHeadersMap();
    }
    /**
     * <code>map&lt;string, string&gt; headers = 4;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getHeadersMap() {
      return java.util.Collections.unmodifiableMap(
          internalGetHeaders());
    }
    /**
     * <code>map&lt;string, string&gt; headers = 4;</code>
     */
    @java.lang.Override

    public java.lang.String getHeadersOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      key.getClass();
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetHeaders();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; headers = 4;</code>
     */
    @java.lang.Override

    public java.lang.String getHeadersOrThrow(
        java.lang.String key) {
      key.getClass();
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetHeaders();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    /**
     * <code>map&lt;string, string&gt; headers = 4;</code>
     */
    private java.util.Map<java.lang.String, java.lang.String>
    getMutableHeadersMap() {
      return internalGetMutableHeaders();
    }

    public static final int FOLLOW_REDIRECTS_FIELD_NUMBER = 5;
    private boolean followRedirects_;
    /**
     * <code>required bool follow_redirects = 5;</code>
     * @return Whether the followRedirects field is set.
     */
    @java.lang.Override
    public boolean hasFollowRedirects() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required bool follow_redirects = 5;</code>
     * @return The followRedirects.
     */
    @java.lang.Override
    public boolean getFollowRedirects() {
      return followRedirects_;
    }
    /**
     * <code>required bool follow_redirects = 5;</code>
     * @param value The followRedirects to set.
     */
    private void setFollowRedirects(boolean value) {
      bitField0_ |= 0x00000008;
      followRedirects_ = value;
    }
    /**
     * <code>required bool follow_redirects = 5;</code>
     */
    private void clearFollowRedirects() {
      bitField0_ = (bitField0_ & ~0x00000008);
      followRedirects_ = false;
    }

    public static final int USE_CACHES_FIELD_NUMBER = 6;
    private boolean useCaches_;
    /**
     * <code>required bool use_caches = 6;</code>
     * @return Whether the useCaches field is set.
     */
    @java.lang.Override
    public boolean hasUseCaches() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required bool use_caches = 6;</code>
     * @return The useCaches.
     */
    @java.lang.Override
    public boolean getUseCaches() {
      return useCaches_;
    }
    /**
     * <code>required bool use_caches = 6;</code>
     * @param value The useCaches to set.
     */
    private void setUseCaches(boolean value) {
      bitField0_ |= 0x00000010;
      useCaches_ = value;
    }
    /**
     * <code>required bool use_caches = 6;</code>
     */
    private void clearUseCaches() {
      bitField0_ = (bitField0_ & ~0x00000010);
      useCaches_ = false;
    }

    public static final int CONNECT_TIMEOUT_SECS_FIELD_NUMBER = 7;
    private int connectTimeoutSecs_;
    /**
     * <code>required int32 connect_timeout_secs = 7;</code>
     * @return Whether the connectTimeoutSecs field is set.
     */
    @java.lang.Override
    public boolean hasConnectTimeoutSecs() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>required int32 connect_timeout_secs = 7;</code>
     * @return The connectTimeoutSecs.
     */
    @java.lang.Override
    public int getConnectTimeoutSecs() {
      return connectTimeoutSecs_;
    }
    /**
     * <code>required int32 connect_timeout_secs = 7;</code>
     * @param value The connectTimeoutSecs to set.
     */
    private void setConnectTimeoutSecs(int value) {
      bitField0_ |= 0x00000020;
      connectTimeoutSecs_ = value;
    }
    /**
     * <code>required int32 connect_timeout_secs = 7;</code>
     */
    private void clearConnectTimeoutSecs() {
      bitField0_ = (bitField0_ & ~0x00000020);
      connectTimeoutSecs_ = 0;
    }

    public static final int READ_TIMEOUT_SECS_FIELD_NUMBER = 8;
    private int readTimeoutSecs_;
    /**
     * <code>required int32 read_timeout_secs = 8;</code>
     * @return Whether the readTimeoutSecs field is set.
     */
    @java.lang.Override
    public boolean hasReadTimeoutSecs() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>required int32 read_timeout_secs = 8;</code>
     * @return The readTimeoutSecs.
     */
    @java.lang.Override
    public int getReadTimeoutSecs() {
      return readTimeoutSecs_;
    }
    /**
     * <code>required int32 read_timeout_secs = 8;</code>
     * @param value The readTimeoutSecs to set.
     */
    private void setReadTimeoutSecs(int value) {
      bitField0_ |= 0x00000040;
      readTimeoutSecs_ = value;
    }
    /**
     * <code>required int32 read_timeout_secs = 8;</code>
     */
    private void clearReadTimeoutSecs() {
      bitField0_ = (bitField0_ & ~0x00000040);
      readTimeoutSecs_ = 0;
    }

    public static uniffi.nimbus.httpconfig.MsgTypes.Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static uniffi.nimbus.httpconfig.MsgTypes.Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static uniffi.nimbus.httpconfig.MsgTypes.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static uniffi.nimbus.httpconfig.MsgTypes.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static uniffi.nimbus.httpconfig.MsgTypes.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static uniffi.nimbus.httpconfig.MsgTypes.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static uniffi.nimbus.httpconfig.MsgTypes.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static uniffi.nimbus.httpconfig.MsgTypes.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static uniffi.nimbus.httpconfig.MsgTypes.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static uniffi.nimbus.httpconfig.MsgTypes.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static uniffi.nimbus.httpconfig.MsgTypes.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static uniffi.nimbus.httpconfig.MsgTypes.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(uniffi.nimbus.httpconfig.MsgTypes.Request prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code uniffi.nimbus.httpconfig.protobuf.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          uniffi.nimbus.httpconfig.MsgTypes.Request, Builder> implements
        // @@protoc_insertion_point(builder_implements:uniffi.nimbus.httpconfig.protobuf.Request)
        uniffi.nimbus.httpconfig.MsgTypes.RequestOrBuilder {
      // Construct using uniffi.nimbus.httpconfig.MsgTypes.Request.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required .uniffi.nimbus.httpconfig.protobuf.Request.Method method = 1;</code>
       * @return Whether the method field is set.
       */
      @java.lang.Override
      public boolean hasMethod() {
        return instance.hasMethod();
      }
      /**
       * <code>required .uniffi.nimbus.httpconfig.protobuf.Request.Method method = 1;</code>
       * @return The method.
       */
      @java.lang.Override
      public uniffi.nimbus.httpconfig.MsgTypes.Request.Method getMethod() {
        return instance.getMethod();
      }
      /**
       * <code>required .uniffi.nimbus.httpconfig.protobuf.Request.Method method = 1;</code>
       * @param value The enum numeric value on the wire for method to set.
       * @return This builder for chaining.
       */
      public Builder setMethod(uniffi.nimbus.httpconfig.MsgTypes.Request.Method value) {
        copyOnWrite();
        instance.setMethod(value);
        return this;
      }
      /**
       * <code>required .uniffi.nimbus.httpconfig.protobuf.Request.Method method = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMethod() {
        copyOnWrite();
        instance.clearMethod();
        return this;
      }

      /**
       * <code>required string url = 2;</code>
       * @return Whether the url field is set.
       */
      @java.lang.Override
      public boolean hasUrl() {
        return instance.hasUrl();
      }
      /**
       * <code>required string url = 2;</code>
       * @return The url.
       */
      @java.lang.Override
      public java.lang.String getUrl() {
        return instance.getUrl();
      }
      /**
       * <code>required string url = 2;</code>
       * @return The bytes for url.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getUrlBytes() {
        return instance.getUrlBytes();
      }
      /**
       * <code>required string url = 2;</code>
       * @param value The url to set.
       * @return This builder for chaining.
       */
      public Builder setUrl(
          java.lang.String value) {
        copyOnWrite();
        instance.setUrl(value);
        return this;
      }
      /**
       * <code>required string url = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUrl() {
        copyOnWrite();
        instance.clearUrl();
        return this;
      }
      /**
       * <code>required string url = 2;</code>
       * @param value The bytes for url to set.
       * @return This builder for chaining.
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUrlBytes(value);
        return this;
      }

      /**
       * <code>optional bytes body = 3;</code>
       * @return Whether the body field is set.
       */
      @java.lang.Override
      public boolean hasBody() {
        return instance.hasBody();
      }
      /**
       * <code>optional bytes body = 3;</code>
       * @return The body.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getBody() {
        return instance.getBody();
      }
      /**
       * <code>optional bytes body = 3;</code>
       * @param value The body to set.
       * @return This builder for chaining.
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setBody(value);
        return this;
      }
      /**
       * <code>optional bytes body = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBody() {
        copyOnWrite();
        instance.clearBody();
        return this;
      }

      @java.lang.Override

      public int getHeadersCount() {
        return instance.getHeadersMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; headers = 4;</code>
       */
      @java.lang.Override

      public boolean containsHeaders(
          java.lang.String key) {
        key.getClass();
        return instance.getHeadersMap().containsKey(key);
      }

      public Builder clearHeaders() {
        copyOnWrite();
        instance.getMutableHeadersMap().clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; headers = 4;</code>
       */

      public Builder removeHeaders(
          java.lang.String key) {
        key.getClass();
        copyOnWrite();
        instance.getMutableHeadersMap().remove(key);
        return this;
      }
      /**
       * Use {@link #getHeadersMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getHeaders() {
        return getHeadersMap();
      }
      /**
       * <code>map&lt;string, string&gt; headers = 4;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, java.lang.String> getHeadersMap() {
        return java.util.Collections.unmodifiableMap(
            instance.getHeadersMap());
      }
      /**
       * <code>map&lt;string, string&gt; headers = 4;</code>
       */
      @java.lang.Override

      public java.lang.String getHeadersOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        key.getClass();
        java.util.Map<java.lang.String, java.lang.String> map =
            instance.getHeadersMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; headers = 4;</code>
       */
      @java.lang.Override

      public java.lang.String getHeadersOrThrow(
          java.lang.String key) {
        key.getClass();
        java.util.Map<java.lang.String, java.lang.String> map =
            instance.getHeadersMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      /**
       * <code>map&lt;string, string&gt; headers = 4;</code>
       */
      public Builder putHeaders(
          java.lang.String key,
          java.lang.String value) {
        key.getClass();
        value.getClass();
        copyOnWrite();
        instance.getMutableHeadersMap().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; headers = 4;</code>
       */
      public Builder putAllHeaders(
          java.util.Map<java.lang.String, java.lang.String> values) {
        copyOnWrite();
        instance.getMutableHeadersMap().putAll(values);
        return this;
      }

      /**
       * <code>required bool follow_redirects = 5;</code>
       * @return Whether the followRedirects field is set.
       */
      @java.lang.Override
      public boolean hasFollowRedirects() {
        return instance.hasFollowRedirects();
      }
      /**
       * <code>required bool follow_redirects = 5;</code>
       * @return The followRedirects.
       */
      @java.lang.Override
      public boolean getFollowRedirects() {
        return instance.getFollowRedirects();
      }
      /**
       * <code>required bool follow_redirects = 5;</code>
       * @param value The followRedirects to set.
       * @return This builder for chaining.
       */
      public Builder setFollowRedirects(boolean value) {
        copyOnWrite();
        instance.setFollowRedirects(value);
        return this;
      }
      /**
       * <code>required bool follow_redirects = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearFollowRedirects() {
        copyOnWrite();
        instance.clearFollowRedirects();
        return this;
      }

      /**
       * <code>required bool use_caches = 6;</code>
       * @return Whether the useCaches field is set.
       */
      @java.lang.Override
      public boolean hasUseCaches() {
        return instance.hasUseCaches();
      }
      /**
       * <code>required bool use_caches = 6;</code>
       * @return The useCaches.
       */
      @java.lang.Override
      public boolean getUseCaches() {
        return instance.getUseCaches();
      }
      /**
       * <code>required bool use_caches = 6;</code>
       * @param value The useCaches to set.
       * @return This builder for chaining.
       */
      public Builder setUseCaches(boolean value) {
        copyOnWrite();
        instance.setUseCaches(value);
        return this;
      }
      /**
       * <code>required bool use_caches = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearUseCaches() {
        copyOnWrite();
        instance.clearUseCaches();
        return this;
      }

      /**
       * <code>required int32 connect_timeout_secs = 7;</code>
       * @return Whether the connectTimeoutSecs field is set.
       */
      @java.lang.Override
      public boolean hasConnectTimeoutSecs() {
        return instance.hasConnectTimeoutSecs();
      }
      /**
       * <code>required int32 connect_timeout_secs = 7;</code>
       * @return The connectTimeoutSecs.
       */
      @java.lang.Override
      public int getConnectTimeoutSecs() {
        return instance.getConnectTimeoutSecs();
      }
      /**
       * <code>required int32 connect_timeout_secs = 7;</code>
       * @param value The connectTimeoutSecs to set.
       * @return This builder for chaining.
       */
      public Builder setConnectTimeoutSecs(int value) {
        copyOnWrite();
        instance.setConnectTimeoutSecs(value);
        return this;
      }
      /**
       * <code>required int32 connect_timeout_secs = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearConnectTimeoutSecs() {
        copyOnWrite();
        instance.clearConnectTimeoutSecs();
        return this;
      }

      /**
       * <code>required int32 read_timeout_secs = 8;</code>
       * @return Whether the readTimeoutSecs field is set.
       */
      @java.lang.Override
      public boolean hasReadTimeoutSecs() {
        return instance.hasReadTimeoutSecs();
      }
      /**
       * <code>required int32 read_timeout_secs = 8;</code>
       * @return The readTimeoutSecs.
       */
      @java.lang.Override
      public int getReadTimeoutSecs() {
        return instance.getReadTimeoutSecs();
      }
      /**
       * <code>required int32 read_timeout_secs = 8;</code>
       * @param value The readTimeoutSecs to set.
       * @return This builder for chaining.
       */
      public Builder setReadTimeoutSecs(int value) {
        copyOnWrite();
        instance.setReadTimeoutSecs(value);
        return this;
      }
      /**
       * <code>required int32 read_timeout_secs = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearReadTimeoutSecs() {
        copyOnWrite();
        instance.clearReadTimeoutSecs();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:uniffi.nimbus.httpconfig.protobuf.Request)
    }
    private byte memoizedIsInitialized = 2;
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new uniffi.nimbus.httpconfig.MsgTypes.Request();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "method_",
              uniffi.nimbus.httpconfig.MsgTypes.Request.Method.internalGetVerifier(),
              "url_",
              "body_",
              "headers_",
              HeadersDefaultEntryHolder.defaultEntry,
              "followRedirects_",
              "useCaches_",
              "connectTimeoutSecs_",
              "readTimeoutSecs_",
            };
            java.lang.String info =
                "\u0001\b\u0000\u0001\u0001\b\b\u0001\u0000\u0006\u0001\u050c\u0000\u0002\u0508\u0001" +
                "\u0003\n\u0002\u00042\u0005\u0507\u0003\u0006\u0507\u0004\u0007\u0504\u0005\b\u0504" +
                "\u0006";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<uniffi.nimbus.httpconfig.MsgTypes.Request> parser = PARSER;
          if (parser == null) {
            synchronized (uniffi.nimbus.httpconfig.MsgTypes.Request.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<uniffi.nimbus.httpconfig.MsgTypes.Request>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return memoizedIsInitialized;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:uniffi.nimbus.httpconfig.protobuf.Request)
    private static final uniffi.nimbus.httpconfig.MsgTypes.Request DEFAULT_INSTANCE;
    static {
      Request defaultInstance = new Request();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Request.class, defaultInstance);
    }

    public static uniffi.nimbus.httpconfig.MsgTypes.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Request> PARSER;

    public static com.google.protobuf.Parser<Request> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:uniffi.nimbus.httpconfig.protobuf.Response)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * If this is present, nothing else is.
     * </pre>
     *
     * <code>optional string exception_message = 1;</code>
     * @return Whether the exceptionMessage field is set.
     */
    boolean hasExceptionMessage();
    /**
     * <pre>
     * If this is present, nothing else is.
     * </pre>
     *
     * <code>optional string exception_message = 1;</code>
     * @return The exceptionMessage.
     */
    java.lang.String getExceptionMessage();
    /**
     * <pre>
     * If this is present, nothing else is.
     * </pre>
     *
     * <code>optional string exception_message = 1;</code>
     * @return The bytes for exceptionMessage.
     */
    com.google.protobuf.ByteString
        getExceptionMessageBytes();

    /**
     * <code>optional string url = 2;</code>
     * @return Whether the url field is set.
     */
    boolean hasUrl();
    /**
     * <code>optional string url = 2;</code>
     * @return The url.
     */
    java.lang.String getUrl();
    /**
     * <code>optional string url = 2;</code>
     * @return The bytes for url.
     */
    com.google.protobuf.ByteString
        getUrlBytes();

    /**
     * <code>optional int32 status = 3;</code>
     * @return Whether the status field is set.
     */
    boolean hasStatus();
    /**
     * <code>optional int32 status = 3;</code>
     * @return The status.
     */
    int getStatus();

    /**
     * <code>optional bytes body = 4;</code>
     * @return Whether the body field is set.
     */
    boolean hasBody();
    /**
     * <code>optional bytes body = 4;</code>
     * @return The body.
     */
    com.google.protobuf.ByteString getBody();

    /**
     * <code>map&lt;string, string&gt; headers = 5;</code>
     */
    int getHeadersCount();
    /**
     * <code>map&lt;string, string&gt; headers = 5;</code>
     */
    boolean containsHeaders(
        java.lang.String key);
    /**
     * Use {@link #getHeadersMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getHeaders();
    /**
     * <code>map&lt;string, string&gt; headers = 5;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getHeadersMap();
    /**
     * <code>map&lt;string, string&gt; headers = 5;</code>
     */

    java.lang.String getHeadersOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; headers = 5;</code>
     */

    java.lang.String getHeadersOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code uniffi.nimbus.httpconfig.protobuf.Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessageLite<
          Response, Response.Builder> implements
      // @@protoc_insertion_point(message_implements:uniffi.nimbus.httpconfig.protobuf.Response)
      ResponseOrBuilder {
    private Response() {
      exceptionMessage_ = "";
      url_ = "";
      body_ = com.google.protobuf.ByteString.EMPTY;
    }
    private int bitField0_;
    public static final int EXCEPTION_MESSAGE_FIELD_NUMBER = 1;
    private java.lang.String exceptionMessage_;
    /**
     * <pre>
     * If this is present, nothing else is.
     * </pre>
     *
     * <code>optional string exception_message = 1;</code>
     * @return Whether the exceptionMessage field is set.
     */
    @java.lang.Override
    public boolean hasExceptionMessage() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * If this is present, nothing else is.
     * </pre>
     *
     * <code>optional string exception_message = 1;</code>
     * @return The exceptionMessage.
     */
    @java.lang.Override
    public java.lang.String getExceptionMessage() {
      return exceptionMessage_;
    }
    /**
     * <pre>
     * If this is present, nothing else is.
     * </pre>
     *
     * <code>optional string exception_message = 1;</code>
     * @return The bytes for exceptionMessage.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getExceptionMessageBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(exceptionMessage_);
    }
    /**
     * <pre>
     * If this is present, nothing else is.
     * </pre>
     *
     * <code>optional string exception_message = 1;</code>
     * @param value The exceptionMessage to set.
     */
    private void setExceptionMessage(
        java.lang.String value) {
      value.getClass();
  bitField0_ |= 0x00000001;
      exceptionMessage_ = value;
    }
    /**
     * <pre>
     * If this is present, nothing else is.
     * </pre>
     *
     * <code>optional string exception_message = 1;</code>
     */
    private void clearExceptionMessage() {
      bitField0_ = (bitField0_ & ~0x00000001);
      exceptionMessage_ = getDefaultInstance().getExceptionMessage();
    }
    /**
     * <pre>
     * If this is present, nothing else is.
     * </pre>
     *
     * <code>optional string exception_message = 1;</code>
     * @param value The bytes for exceptionMessage to set.
     */
    private void setExceptionMessageBytes(
        com.google.protobuf.ByteString value) {
      exceptionMessage_ = value.toStringUtf8();
      bitField0_ |= 0x00000001;
    }

    public static final int URL_FIELD_NUMBER = 2;
    private java.lang.String url_;
    /**
     * <code>optional string url = 2;</code>
     * @return Whether the url field is set.
     */
    @java.lang.Override
    public boolean hasUrl() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string url = 2;</code>
     * @return The url.
     */
    @java.lang.Override
    public java.lang.String getUrl() {
      return url_;
    }
    /**
     * <code>optional string url = 2;</code>
     * @return The bytes for url.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUrlBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(url_);
    }
    /**
     * <code>optional string url = 2;</code>
     * @param value The url to set.
     */
    private void setUrl(
        java.lang.String value) {
      value.getClass();
  bitField0_ |= 0x00000002;
      url_ = value;
    }
    /**
     * <code>optional string url = 2;</code>
     */
    private void clearUrl() {
      bitField0_ = (bitField0_ & ~0x00000002);
      url_ = getDefaultInstance().getUrl();
    }
    /**
     * <code>optional string url = 2;</code>
     * @param value The bytes for url to set.
     */
    private void setUrlBytes(
        com.google.protobuf.ByteString value) {
      url_ = value.toStringUtf8();
      bitField0_ |= 0x00000002;
    }

    public static final int STATUS_FIELD_NUMBER = 3;
    private int status_;
    /**
     * <code>optional int32 status = 3;</code>
     * @return Whether the status field is set.
     */
    @java.lang.Override
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 status = 3;</code>
     * @return The status.
     */
    @java.lang.Override
    public int getStatus() {
      return status_;
    }
    /**
     * <code>optional int32 status = 3;</code>
     * @param value The status to set.
     */
    private void setStatus(int value) {
      bitField0_ |= 0x00000004;
      status_ = value;
    }
    /**
     * <code>optional int32 status = 3;</code>
     */
    private void clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000004);
      status_ = 0;
    }

    public static final int BODY_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString body_;
    /**
     * <code>optional bytes body = 4;</code>
     * @return Whether the body field is set.
     */
    @java.lang.Override
    public boolean hasBody() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional bytes body = 4;</code>
     * @return The body.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }
    /**
     * <code>optional bytes body = 4;</code>
     * @param value The body to set.
     */
    private void setBody(com.google.protobuf.ByteString value) {
      value.getClass();
  bitField0_ |= 0x00000008;
      body_ = value;
    }
    /**
     * <code>optional bytes body = 4;</code>
     */
    private void clearBody() {
      bitField0_ = (bitField0_ & ~0x00000008);
      body_ = getDefaultInstance().getBody();
    }

    public static final int HEADERS_FIELD_NUMBER = 5;
    private static final class HeadersDefaultEntryHolder {
      static final com.google.protobuf.MapEntryLite<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntryLite
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapFieldLite<
        java.lang.String, java.lang.String> headers_ =
            com.google.protobuf.MapFieldLite.emptyMapField();
    private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.String>
    internalGetHeaders() {
      return headers_;
    }
    private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.String>
    internalGetMutableHeaders() {
      if (!headers_.isMutable()) {
        headers_ = headers_.mutableCopy();
      }
      return headers_;
    }
    @java.lang.Override

    public int getHeadersCount() {
      return internalGetHeaders().size();
    }
    /**
     * <code>map&lt;string, string&gt; headers = 5;</code>
     */
    @java.lang.Override

    public boolean containsHeaders(
        java.lang.String key) {
      key.getClass();
      return internalGetHeaders().containsKey(key);
    }
    /**
     * Use {@link #getHeadersMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getHeaders() {
      return getHeadersMap();
    }
    /**
     * <code>map&lt;string, string&gt; headers = 5;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getHeadersMap() {
      return java.util.Collections.unmodifiableMap(
          internalGetHeaders());
    }
    /**
     * <code>map&lt;string, string&gt; headers = 5;</code>
     */
    @java.lang.Override

    public java.lang.String getHeadersOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      key.getClass();
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetHeaders();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; headers = 5;</code>
     */
    @java.lang.Override

    public java.lang.String getHeadersOrThrow(
        java.lang.String key) {
      key.getClass();
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetHeaders();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    /**
     * <code>map&lt;string, string&gt; headers = 5;</code>
     */
    private java.util.Map<java.lang.String, java.lang.String>
    getMutableHeadersMap() {
      return internalGetMutableHeaders();
    }

    public static uniffi.nimbus.httpconfig.MsgTypes.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static uniffi.nimbus.httpconfig.MsgTypes.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static uniffi.nimbus.httpconfig.MsgTypes.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static uniffi.nimbus.httpconfig.MsgTypes.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static uniffi.nimbus.httpconfig.MsgTypes.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static uniffi.nimbus.httpconfig.MsgTypes.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static uniffi.nimbus.httpconfig.MsgTypes.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static uniffi.nimbus.httpconfig.MsgTypes.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static uniffi.nimbus.httpconfig.MsgTypes.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static uniffi.nimbus.httpconfig.MsgTypes.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static uniffi.nimbus.httpconfig.MsgTypes.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static uniffi.nimbus.httpconfig.MsgTypes.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(uniffi.nimbus.httpconfig.MsgTypes.Response prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code uniffi.nimbus.httpconfig.protobuf.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          uniffi.nimbus.httpconfig.MsgTypes.Response, Builder> implements
        // @@protoc_insertion_point(builder_implements:uniffi.nimbus.httpconfig.protobuf.Response)
        uniffi.nimbus.httpconfig.MsgTypes.ResponseOrBuilder {
      // Construct using uniffi.nimbus.httpconfig.MsgTypes.Response.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * If this is present, nothing else is.
       * </pre>
       *
       * <code>optional string exception_message = 1;</code>
       * @return Whether the exceptionMessage field is set.
       */
      @java.lang.Override
      public boolean hasExceptionMessage() {
        return instance.hasExceptionMessage();
      }
      /**
       * <pre>
       * If this is present, nothing else is.
       * </pre>
       *
       * <code>optional string exception_message = 1;</code>
       * @return The exceptionMessage.
       */
      @java.lang.Override
      public java.lang.String getExceptionMessage() {
        return instance.getExceptionMessage();
      }
      /**
       * <pre>
       * If this is present, nothing else is.
       * </pre>
       *
       * <code>optional string exception_message = 1;</code>
       * @return The bytes for exceptionMessage.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getExceptionMessageBytes() {
        return instance.getExceptionMessageBytes();
      }
      /**
       * <pre>
       * If this is present, nothing else is.
       * </pre>
       *
       * <code>optional string exception_message = 1;</code>
       * @param value The exceptionMessage to set.
       * @return This builder for chaining.
       */
      public Builder setExceptionMessage(
          java.lang.String value) {
        copyOnWrite();
        instance.setExceptionMessage(value);
        return this;
      }
      /**
       * <pre>
       * If this is present, nothing else is.
       * </pre>
       *
       * <code>optional string exception_message = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearExceptionMessage() {
        copyOnWrite();
        instance.clearExceptionMessage();
        return this;
      }
      /**
       * <pre>
       * If this is present, nothing else is.
       * </pre>
       *
       * <code>optional string exception_message = 1;</code>
       * @param value The bytes for exceptionMessage to set.
       * @return This builder for chaining.
       */
      public Builder setExceptionMessageBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setExceptionMessageBytes(value);
        return this;
      }

      /**
       * <code>optional string url = 2;</code>
       * @return Whether the url field is set.
       */
      @java.lang.Override
      public boolean hasUrl() {
        return instance.hasUrl();
      }
      /**
       * <code>optional string url = 2;</code>
       * @return The url.
       */
      @java.lang.Override
      public java.lang.String getUrl() {
        return instance.getUrl();
      }
      /**
       * <code>optional string url = 2;</code>
       * @return The bytes for url.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getUrlBytes() {
        return instance.getUrlBytes();
      }
      /**
       * <code>optional string url = 2;</code>
       * @param value The url to set.
       * @return This builder for chaining.
       */
      public Builder setUrl(
          java.lang.String value) {
        copyOnWrite();
        instance.setUrl(value);
        return this;
      }
      /**
       * <code>optional string url = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUrl() {
        copyOnWrite();
        instance.clearUrl();
        return this;
      }
      /**
       * <code>optional string url = 2;</code>
       * @param value The bytes for url to set.
       * @return This builder for chaining.
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUrlBytes(value);
        return this;
      }

      /**
       * <code>optional int32 status = 3;</code>
       * @return Whether the status field is set.
       */
      @java.lang.Override
      public boolean hasStatus() {
        return instance.hasStatus();
      }
      /**
       * <code>optional int32 status = 3;</code>
       * @return The status.
       */
      @java.lang.Override
      public int getStatus() {
        return instance.getStatus();
      }
      /**
       * <code>optional int32 status = 3;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(int value) {
        copyOnWrite();
        instance.setStatus(value);
        return this;
      }
      /**
       * <code>optional int32 status = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        copyOnWrite();
        instance.clearStatus();
        return this;
      }

      /**
       * <code>optional bytes body = 4;</code>
       * @return Whether the body field is set.
       */
      @java.lang.Override
      public boolean hasBody() {
        return instance.hasBody();
      }
      /**
       * <code>optional bytes body = 4;</code>
       * @return The body.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getBody() {
        return instance.getBody();
      }
      /**
       * <code>optional bytes body = 4;</code>
       * @param value The body to set.
       * @return This builder for chaining.
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setBody(value);
        return this;
      }
      /**
       * <code>optional bytes body = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearBody() {
        copyOnWrite();
        instance.clearBody();
        return this;
      }

      @java.lang.Override

      public int getHeadersCount() {
        return instance.getHeadersMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; headers = 5;</code>
       */
      @java.lang.Override

      public boolean containsHeaders(
          java.lang.String key) {
        key.getClass();
        return instance.getHeadersMap().containsKey(key);
      }

      public Builder clearHeaders() {
        copyOnWrite();
        instance.getMutableHeadersMap().clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; headers = 5;</code>
       */

      public Builder removeHeaders(
          java.lang.String key) {
        key.getClass();
        copyOnWrite();
        instance.getMutableHeadersMap().remove(key);
        return this;
      }
      /**
       * Use {@link #getHeadersMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getHeaders() {
        return getHeadersMap();
      }
      /**
       * <code>map&lt;string, string&gt; headers = 5;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, java.lang.String> getHeadersMap() {
        return java.util.Collections.unmodifiableMap(
            instance.getHeadersMap());
      }
      /**
       * <code>map&lt;string, string&gt; headers = 5;</code>
       */
      @java.lang.Override

      public java.lang.String getHeadersOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        key.getClass();
        java.util.Map<java.lang.String, java.lang.String> map =
            instance.getHeadersMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; headers = 5;</code>
       */
      @java.lang.Override

      public java.lang.String getHeadersOrThrow(
          java.lang.String key) {
        key.getClass();
        java.util.Map<java.lang.String, java.lang.String> map =
            instance.getHeadersMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      /**
       * <code>map&lt;string, string&gt; headers = 5;</code>
       */
      public Builder putHeaders(
          java.lang.String key,
          java.lang.String value) {
        key.getClass();
        value.getClass();
        copyOnWrite();
        instance.getMutableHeadersMap().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; headers = 5;</code>
       */
      public Builder putAllHeaders(
          java.util.Map<java.lang.String, java.lang.String> values) {
        copyOnWrite();
        instance.getMutableHeadersMap().putAll(values);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:uniffi.nimbus.httpconfig.protobuf.Response)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new uniffi.nimbus.httpconfig.MsgTypes.Response();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "exceptionMessage_",
              "url_",
              "status_",
              "body_",
              "headers_",
              HeadersDefaultEntryHolder.defaultEntry,
            };
            java.lang.String info =
                "\u0001\u0005\u0000\u0001\u0001\u0005\u0005\u0001\u0000\u0000\u0001\b\u0000\u0002" +
                "\b\u0001\u0003\u0004\u0002\u0004\n\u0003\u00052";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<uniffi.nimbus.httpconfig.MsgTypes.Response> parser = PARSER;
          if (parser == null) {
            synchronized (uniffi.nimbus.httpconfig.MsgTypes.Response.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<uniffi.nimbus.httpconfig.MsgTypes.Response>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:uniffi.nimbus.httpconfig.protobuf.Response)
    private static final uniffi.nimbus.httpconfig.MsgTypes.Response DEFAULT_INSTANCE;
    static {
      Response defaultInstance = new Response();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Response.class, defaultInstance);
    }

    public static uniffi.nimbus.httpconfig.MsgTypes.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Response> PARSER;

    public static com.google.protobuf.Parser<Response> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
