libraryVersion: 0.1.0
groupId: uniffi
artifactId: nimbus
description: A uniffi generated android bindings for the Nimbus SDK
libUrl: https://github.com/mozilla/glean
libVcsUrl: https://github.com/mozilla/glean.git
libLicense: MPL-2.0
libLicenseUrl: https://www.mozilla.org/en-US/MPL/2.0/